# --- 
# Python script to send music metadata from DJ Pro Classic radio automation by Axel Technology to an Orban RDS Encoder, displaying song information on listeners’ car radios.
# Read Dj Pro Classic XML and send RT string to Orban via telnet.
# ---
# Stefano Podestà - 30/03/2021
# Ver. 1.0
# ---

import threading  # Allows running functions in parallel or scheduled
import telnetlib  # Library to connect to devices via telnet
import xml.etree.ElementTree as et  # For reading and processing xml files

# Configuration of the RDS encoder host and port
host = '192.168.1.2'
port = '22201'

# Main function to read Dj Pro Classic XML and send text to Orban
def scanxml():
    # Recall the function every 3 seconds (recursive timer)
    threading.Timer(3.0, scanxml).start()

    # Parse the XML file generated by Dj Pro Classic
    mytree = et.parse('P:\\rds\\playlist.xml')
    myroot = mytree.getroot()

    counter = 0  # Counter for elements processed

    # Loop through all 'element' nodes in the xml
    for x in myroot.findall('element'):
        author = x.find('author').text  # Song author
        title = x.find('title').text    # Song title

        # If author is missing, use only the title
        if author is None:
            author = " "
            text = title
            counter += 1
        else:
            text = author + " - " + title  # Combine author and title
            counter += 1

        # Send only the first element found
        if counter == 1:
            print("Script RDS Dj Pro Classic/Orban - On air text:")
            print(text)  # Print the text being sent

            # Open a telnet connection to the Orban RDS encoder
            tn = telnetlib.Telnet(host, port)
            cmd = "RT=" + text + "\n"  # RDS command for on air text
            tn.write(cmd.encode("ascii"))  # Send the command
            tn.close()  # Close the telnet connection
            
            del text  # Clean up variable

# Start the function when the script runs
scanxml()